/**
 * Profil d'atelier : capacités de débit et d'usinage (bois et métal), seuils de fabrication
 * (valeurs à valider).
 */
export {
  DEFAULT_WORKSHOP_PROFILE,
  WOOD_MATERIALS,
  WORKSHOP_PROVENANCE,
  WorkshopProfileSchema,
  isWoodMaterial,
  resolveWorkshopProfile,
  smallestAvailable,
  type SettingProvenance,
  type WoodMaterialId,
  type WoodSettingKey,
  type WorkshopProfile,
  type WorkshopProfileInput,
} from "./profile.js";
export {
  BENDING_DIRECTIONS,
  BENDING_FAMILIES,
  BEND_METHODS,
  DEFAULT_SAW_KERF,
  DEFAULT_PLATE_ROLLING,
  type PlateRolling,
  ProfileBendingSchema,
  minProfileBendRadius,
  type ProfileBending,
  BendLawSchema,
  DEFAULT_K_FACTOR,
  DEFAULT_METAL_PROFILE,
  METAL_PROVENANCE,
  MetalProfileInputSchema,
  STEEL_GRADES,
  SheetFormatSchema,
  bendAllowance,
  din6935Correction,
  findBendLaw,
  minBendRadiusFactor,
  outsideSetback,
  resolveBend,
  resolveMetalProfile,
  type BendLaw,
  type BendMethod,
  type MetalProfile,
  type MetalProfileInput,
  type MetalProvenance,
  type MetalSettingKey,
  type ResolvedBend,
  type SheetFormat,
  type SteelGrade,
} from "./metal.js";
export { COST_TIME_FIELDS, CostRatesSchema, type CostRates } from "./costs.js";
